### ISSUE TITLE
move the style code to related CSS file

### ISSUE THREAD

**Issue by oladhari** [Jin-prgrmng/my_portfolio_site#7]
you have added style in HTML file which is not the most accurate way to do
please gather all CSS code in one unique file

- [x] copy the style code from HTML file to CSS file
- [x] delete the style from HTML file
- [ ] test the application

all these operations should be done in one PR
no need to open a PR for every commit

**Comment by oladhari** [comment]
how you do 2 PRs? why you create 2 branches???
just do one branch with all needed changes and do commit !
do you know how to do commit?

**Comment by Jin-prgrmng** [comment]
sorry.
I intend to commit. but in fact, I don't.
I learn "commit" again...

**Comment by Jin-prgrmng** [comment]
I learn about Github more.
So I want to start again.

**Comment by oladhari** [comment]
ok no worries, please do a PR with all needed changes

**Comment by Jin-prgrmng** [comment]
Ok. thank you.
I'll use the branch named "Jin-prgrmng-patch-1-2".

**Comment by Jin-prgrmng** [comment]
i send PR to you now.
